- bitcoin/merkle.go
- go-client/query_client_zenbtc.go
- go-client/tx_zenbtc.go
- go.mod
- go.sum
- sidecar/oracle.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
- x/validation/keeper/keeper.go
* fix: bump zenbtc ver + revert temp commits
* fix: temporarily use old func signature for `VerifyBTCLockTransaction`
> fix: bump zenbtc ver + revert temp commits

- app/upgrades.go
- app/upgrades/v5beta8/constants.go
- app/upgrades/v5beta8/upgrade.go
- bitcoin/bitcoin_test.go
- bitcoin/utils.go
- x/treasury/keeper/msg_server_fulfil_signature_request.go
* feat: convert ECDSA Signature to Bitcoin Signature
* Fix test
* fix: handle Bitcoin signatures properly
---------
> fix: convert ECDSA Signature to Bitcoin Signature (#105)

- app/upgrades.go
- app/upgrades/v5beta9/constants.go
- app/upgrades/v5beta9/upgrade.go
- x/treasury/keeper/query_sign_transaction_request_by_id.go
- x/treasury/keeper/query_sign_transaction_requests.go
- x/treasury/keeper/query_signature_request_by_id.go
- x/treasury/keeper/query_signature_requests.go
> fix: sign request queries (#106)

- go.mod
- go.sum
- x/validation/keeper/abci.go
* fix: bump zenbtc + cosmos fork vers
* fix: bump zenbtc ver + add more VE logging
* bump zenbtc
> fix: bump zenbtc + cosmos fork vers, add extra logging (#115)

- x/validation/keeper/abci.go
* fix: multichain VE flow
* optimise `processZenBTCBurnEventsEthereum`
* refactor
* cleanup
* comment styling
> fix: multichain zenbtc VE flow + refactor (#155)

- x/validation/keeper/abci.go
* fix: multichain VE flow
* optimise `processZenBTCBurnEventsEthereum`
* refactor
* cleanup
* comment styling
* fix: updated zenBTC VE flow
* fix/polish
* fix: corrected refactored VE flow
* fixes/polish abci.go
* final fixes + polish
> fix: update VE flow zenBTC (#156)

- app/upgrades.go
- app/upgrades/v5rev9/constants.go
- app/upgrades/v5rev9/upgrade.go
- x/validation/keeper/abci.go
* fix: correctly handle `ErrNotFound` for first time using new key `abci.go`
* add counter field
> fix: correctly handle `ErrNotFound` for first time using new key `abci.go`

- app/upgrades.go
- app/upgrades/v5rev7/constants.go
- app/upgrades/v5rev7/upgrade.go
- go.mod
- go.sum
- shared/zenbtc_keeper_interface.go
- x/validation/keeper/abci.go
* fix: multichain zenBTC logging + polish
* move log
* improve consistency between 4 stages
* refactor to use map for burnevents
* wip
* wip
* refactor for genericity and deduplication
* final refactors
* bump zenbtc ver
> fix: refactor `x/validation/keeper/abci.go` (#163)

- init.sh
- sidecar/config.yaml
- sidecar/eigen_operator_config.yaml
- sidecar/oracle.go
- sidecar/shared/types.go
- sidecar/types.go
* fix: sidecar burnEvent polling
* update config
> fix: sidecar burnEvent polling (#165)

- app/upgrades.go
- app/upgrades/v5rev8/constants.go
- app/upgrades/v5rev8/upgrade.go
- x/validation/keeper/abci_utils.go
* fix: update gas limit `constructUnstakeTx`
> fix: update gas limit `constructUnstakeTx` (#168)

- sidecar/main.go
- sidecar/oracle.go
- sidecar/shared/types.go
- sidecar/types.go
- sidecar/utils.go
* fix: store cleaned up burnEvents on sidecar to prevent churn
* restore comments
* simplify oracle.go
* minor fix
> fix: store cleaned up burnEvents on sidecar to prevent churn + simplify code (#169)

- go.mod
- go.sum
- shared/zenbtc_keeper_interface.go
- sidecar/main.go
- sidecar/oracle.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
* feat: use ntp for time sync
* feat: pararellise requests `fetchAndProcessState`
* feat: optimise store walks by starting from first pending elem
> feat: polish pass (#170)

- x/validation/keeper/genesis.go
- x/validation/keeper/msg_server.go
- x/validation/keeper/params.go
* fix: remove float64
* merge 'main' into fix/remove-float64
* chore: squash module migrations
* Update x/treasury/keeper/keeper.go
* Update x/validation/keeper/abci.go
* chore: update zenbtc interface
* chore: removed migrations except v2
* fix: updated hvparams authority
* fix: remove HVParamsAuthority
* fix: update params types
---------
> fix: update params types (#176)

- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
* fix: `PrepareProposal`
* fix btc blockheader log
* don't log VEFieldZRChainBlockHeight
* fix: `validateOracleData`
> fix: updated VE consensus mechanism (#190)

- go.mod
- go.sum
- shared/zenbtc_keeper_interface.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
* wip
* wip
* feat: implement `checkForRedemptionFulfilment` at end of VE flow
* bump zenbtc ver
> feat: retry redemption after signrequest rejected (#195)

- go.mod
- go.sum
- sidecar/config.yaml
- sidecar/eigen_operator_config.yaml
- sidecar/init_test.go
- sidecar/main.go
- sidecar/oracle.go
- sidecar/pricefeed.go
- sidecar/shared/types.go
- sidecar/types.go
- sidecar/utils.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
- x/validation/keeper/genesis.go
- x/validation/keeper/hv_params.go
- x/validation/migrations/v6/migrations_test.go
- x/validation/migrations/v6/store.go
- x/validation/migrations/v7/migrations_test.go
- x/validation/migrations/v7/store.go
- x/validation/types/hv_params.go
* fix: merge missed changes from hotfix branch
* fix: dynamic sender field in zenbtc stake gas estimation `sidecar`
* fix build
* update config.yaml
* wip
* fix: simplify config
* fix: reverse loop `getStateByEthHeight`
* fix: bump zenbtc ver
* polish reworked VE flow
* use constant for mainnet key
> fix: sidecar polish + merge missed hotfix (#201)

- go.mod
- go.sum
- utils/vote-examiner/main.go
- utils/vote-examiner/types.go
* feat: vote extension examiner
* wip comparison
* include validators that didn't submit VEs
* feat: don't require file input by default
* show consensus addrs
* feat: map validator names to cons addrs
* refactor + polish
* fix: bump zenbtc ver
> feat: vote extension examiner util + bump zenbtc ver (#204)

- app/upgrades.go
- app/upgrades/v5rev8/constants.go
- app/upgrades/v5rev8/upgrade.go
- sidecar/server.go
- utils/vote-examiner/main.go
- x/validation/keeper/abci_types.go
- x/validation/keeper/abci_utils.go
* fix: revert to JSON encoding `sidecar`, add localnet `vote-examiner`
* revert msgpack usage entirely
> fix: revert to JSON encoding, add localnet `vote-examiner` (#209)

- README.md
BREAKING CHANGE: new major version
> feat: trigger v6 release

- Dockerfile
- sidecar/Dockerfile
* fix: wasmvm version in docker
* fix: adjust checksum
> fix: wasmvm version in docker (#216)

- testutil/keeper/zentp.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
- x/validation/types/expected_keepers.go
- x/zentp/keeper/keeper.go
- x/zentp/keeper/msg_server_bridge.go
- x/zentp/keeper/msg_update_params.go
- x/zentp/keeper/msg_update_params_test.go
- x/zentp/keeper/params.go
- x/zentp/keeper/params_test.go
- x/zentp/keeper/query_params.go
- x/zentp/keeper/query_params_test.go
- x/zentp/module/genesis.go
- x/zentp/types/keys.go
- x/zentp/types/params.go
* fix: solana param getter
* fixes
> fix: solana params zentp (#230)

- x/validation/keeper/abci.go
* add error handling and debug prints in processSolanaZenBTCMintEvents
* add error handling and debug prints in processSolanaZenBTCMintEvents
---------
> fix: sol err handling and add debug prints (#244)

- init.sh
- sidecar/oracle.go
- x/treasury/keeper/msg_server_fulfil_key_request.go
- x/treasury/keeper/msg_server_fulfil_key_request_test.go
- x/zentp/types/params.go
* add sidecar info prints for solana mint events; fix zentp sol params
* fix: key rejection
* fix: test
---------
> fix: key rejection, add sidecar logs, fix init.sh (#248)

- go.mod
- go.sum
- sidecar/config.yaml
- sidecar/oracle.go
- sidecar/shared/types.go
* fix: sidecar config
* fix: sidecar polish
* go mod tidy
> fix: sidecar config envs + polish (#249)

- sidecar/init_test.go
- sidecar/main.go
- sidecar/oracle.go
- sidecar/shared/types.go
* fix: sidecar time synchronisation
* wip
* fix: improve time sync
> fix: sidecar time synchronisation (#250)

- go.mod
- go.sum
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
* fix: add more logging (solana zenbtc impl)
* more logging
* wip
* wip
* wip
* feat: retry if no sol mint event is found
* update go mod
> feat: retry sol mint when no events picked up after n blocks (#254)

- app/upgrades.go
- app/upgrades/v6rev3/constants.go
- app/upgrades/v6rev3/upgrade.go
- x/validation/keeper/abci.go
* fix: solana mint event handler + add more logging
* fix: add upgrade files
> fix: solana mint event handler + add more logging (#257)

- app/upgrades.go
- app/upgrades/v6rev5/constants.go
- app/upgrades/v6rev5/upgrade.go
- contracts/solrock/durablenonce_test.go
- sidecar/init_test.go
- x/treasury/types/key.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_utils.go
- x/validation/keeper/keeper.go
- x/validation/keeper/val_state_change.go
- x/validation/keeper/val_state_change_test.go
- x/validation/types/keys.go
- x/zentp/keeper/msg_server_bridge.go
- x/zentp/types/expected_keepers.go
* fix: rockBTC stake power
* fix: CAIP typo
* add test for `TestGetSolanaAccountInfo`
* add test case for `B3ZjSXnczNYXQyhQft6wiNk99sW4NfW3Fe2TwhF7wTH8`
* wip
* fix: split + correct zenbtc and zentp nonce account logic
* finalise
* refactor
* final polish
* add devnet upgrade files
> fix: solana mint logic, rockBTC stake power (#272)

- app/upgrades.go
- app/upgrades/v6rev4/constants.go
- app/upgrades/v6rev4/upgrade.go
- sidecar/shared/types.go
- x/validation/keeper/abci.go
* fix: re-enable solana redemptions + update sidecar params
* fix: add upgrade files
> fix: re-enable solana redemptions + update sidecar params (#282)

- contracts/solrock/durablenonce_test.go
- init.sh
- x/validation/keeper/abci.go
- x/validation/testutil/expected_keepers_mocks.go
- x/validation/types/expected_keepers.go
- x/zentp/keeper/invariants.go
- x/zentp/keeper/invariants_test.go
- x/zentp/keeper/keeper.go
- x/zentp/keeper/msg_server_bridge.go
- x/zentp/keeper/msg_server_bridge_test.go
- x/zentp/testutil/expected_keepers_mocks.go
- x/zentp/types/expected_keepers.go
- x/zentp/types/keys.go
* feat: ROCK supply sanity checks `zentp`
* feat: enforce 1bn ROCK supply cap invariant
* wip
* refactor/cleanup
* wip
* feat: final sanity checks
* feat: proactive invariant check `abci.go`
* wip
* refactor
* refactor
* add tests for ROCK supply invariant logic
* fix test
* fix test
* update init.sh
> feat: `zentp` sanity checks (#293)

- app/upgrades.go
- app/upgrades/v6rev11/constants.go
- app/upgrades/v6rev11/upgrade.go
- x/validation/keeper/abci_types.go
- x/validation/keeper/abci_types_test.go
* feat: v6.11.0 (v6rev11)
* upgrade files
* fix test
> feat: v6.11.0 (v6rev11) (#311)

- sidecar/oracle.go
- sidecar/oracle_test.go
- sidecar/shared/types.go
- sidecar/types.go
- sidecar/utils.go
- x/validation/keeper/abci.go
- x/validation/keeper/abci_types_test.go
* wip
* wip
* wip
* wip
* wip
* wip
* wip
* fix build
* fix test
* cleanup
* fix merge issue
* small config change
* fix tests
* minor
> fix: improve resilience against missed events `sidecar` (#322)

- docs/README.md
- sidecar/oracle.go
- sidecar/shared/types.go
* better logging
* add sequence diagrams
* wip
* wip
* improve diags
* wip
* add detail
* capitalisation
* wip
* polish
* wip
* final polish
* fix err
* simplify
* add detail
* wip
* final
* done
* save on eth calls
* add final detail
* fin
* done
> fix: better logging `sidecar`, add sequence diagrams `docs` (#326)

- .github/workflows/test.yml
- Dockerfile
- go-client/query_client.go
- gopls.json
- tests/integration/key_request_test.go
- tests/integration/zenbtc_solana_mint_test.go
* fix: e2e tests
Also adds zenbtc solana mint flow
* fix: enable all e2e tests
Also increase the ping time on grpc connections to 2 minutes
* fix: increase solana mint timeout
> fix: e2e tests (#332)

- sidecar/backfill_test.go
- sidecar/init_test.go
- sidecar/main.go
- sidecar/oracle_test.go
- sidecar/utils.go
* Update utils.go
* add env var + fallbacks sidecar config
> fix: k8s setup for sidecar (#344)

- .github/workflows/test.yml
- go-client/tx_client.go
- go-client/tx_zentp.go
- sidecar/shared/types.go
- tests/e2e/env.go
- tests/e2e/zentp_solana_test.go
* fix: add first zentp e2e test
* fix: e2e test package rename
* fix: rename e2e tests in CI
* fix: test
* fix: test
* fix: test
> fix: add first zentp e2e test (#343)

- tests/e2e/env.go
- tests/e2e/utils.go
- tests/e2e/zenbtc_eth_mint_test.go
- tests/e2e/zentp_solana_test.go
* fix: zentp burn
* fix: add utils.go
> fix: zentp burn (#353)

- app/upgrades.go
- app/upgrades/v6rev28/constants.go
- app/upgrades/v6rev28/upgrade.go
- x/validation/keeper/keeper.go
- x/validation/keeper/migrations.go
- x/validation/migrations/v9/store.go
- x/validation/migrations/v9/store_test.go
- x/validation/module/module.go
* feat: `v6rev28` / `v6.28.0`
* Update x/validation/module/module.go
---------
> feat: `v6rev28` / `v6.28.0` (#375)

- app/upgrades.go
- app/upgrades/v6rev31/constants.go
- app/upgrades/v6rev31/upgrade.go
- sidecar/oracle.go
- sidecar/shared/types.go
- x/validation/keeper/abci_types.go
- x/validation/keeper/abci_types_test.go
- x/validation/keeper/val_state_change.go
* disable legacy eigen code
* fix sidecar
* Update abci_types_test.go
> feat: `v6rev31` (#392)
